#!/usr/bin/env python3
"""Build the authoritative compile/adaptation inventory for LegacySource."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LEGACY = ROOT / "LegacySource"
PORTING = ROOT / "Porting"

COMPILED_ADAPTATIONS = [
    {
        "legacy": "snake2d/util/misc/CLAMP.cs",
        "java": "snake2d/util/misc/CLAMP.java",
        "compiled": "Scripts/LegacyCompat/SourceClamp.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "snake2d/util/bit/Bits.cs",
        "java": "snake2d/util/bit/Bits.java",
        "compiled": "Scripts/LegacyCompat/PackedBits.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "init/religion/Religion.cs",
        "java": "init/religion/Religion.java",
        "compiled": "Scripts/Data/OriginalGameData.cs; Scripts/Citizens/ReligionRuntime.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "init/religion/RELIGIONS.cs",
        "java": "init/religion/RELIGIONS.java",
        "compiled": "Scripts/Data/OriginalGameData.cs; Scripts/Citizens/ReligionRuntime.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/temple/ROOM_TEMPLES.cs",
        "java": "settlement/room/spirit/temple/ROOM_TEMPLES.java",
        "compiled": "Scripts/Rooms/TempleRuntime.cs; Scripts/Data/OriginalGameData.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/temple/ROOM_TEMPLE.cs",
        "java": "settlement/room/spirit/temple/ROOM_TEMPLE.java",
        "compiled": "Scripts/Rooms/TempleRuntime.cs; Scripts/Rooms/RoomSystem.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/temple/Service.cs",
        "java": "settlement/room/spirit/temple/Service.java",
        "compiled": "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Rooms/TempleRuntime.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/temple/TempleAltar.cs",
        "java": "settlement/room/spirit/temple/TempleAltar.java",
        "compiled": "Scripts/Rooms/TempleRuntime.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/temple/TempleInstance.cs",
        "java": "settlement/room/spirit/temple/TempleInstance.java",
        "compiled": "Scripts/Rooms/TempleRuntime.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/temple/TempleJob.cs",
        "java": "settlement/room/spirit/temple/TempleJob.java",
        "compiled": "Scripts/Rooms/TempleRuntime.cs; Scripts/Simulation/BuildJob.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/shrine/ROOM_SHRINE.cs",
        "java": "settlement/room/spirit/shrine/ROOM_SHRINE.java",
        "compiled": "Scripts/Data/OriginalGameData.cs; Scripts/Rooms/RoomSystem.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/shrine/Service.cs",
        "java": "settlement/room/spirit/shrine/Service.java",
        "compiled": "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Rooms/RoomSystem.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/room/spirit/shrine/ShrineInstance.cs",
        "java": "settlement/room/spirit/shrine/ShrineInstance.java",
        "compiled": "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Rooms/RoomSystem.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/entity/humanoid/ai/service/S_PlanShrine.cs",
        "java": "settlement/entity/humanoid/ai/service/S_PlanShrine.java",
        "compiled": "Scripts/Citizens/CitizenSystem.cs; Scripts/Citizens/ReligionRuntime.cs",
        "status": "compiled_semantic_port",
    },
    {
        "legacy": "settlement/entity/humanoid/ai/service/S_PlanTemple.cs",
        "java": "settlement/entity/humanoid/ai/service/S_PlanTemple.java",
        "compiled": "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/TempleRuntime.cs",
        "status": "compiled_semantic_port",
    },
    *[
        {
            "legacy": path,
            "java": path[:-3] + ".java",
            "compiled": target,
            "status": "compiled_semantic_port",
        }
        for path, target in (
            ("settlement/stats/standing/STANDINGS.cs", "Scripts/Stats/SettlementStandingRuntime.cs"),
            ("settlement/stats/standing/StandingCitizen.cs", "Scripts/Stats/SettlementStandingRuntime.cs"),
            ("settlement/stats/standing/StandingBuff.cs", "Scripts/Stats/SettlementStandingRuntime.cs"),
            ("settlement/stats/standing/StatStanding.cs", "Scripts/Stats/SettlementStandingRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/stats/colls/StatsReproduction.cs", "Scripts/Citizens/CitizenReproductionRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/entity/humanoid/ai/types/child/AIModule_Child.cs", "Scripts/Citizens/CitizenReproductionRuntime.cs; Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/ChildcareRuntime.cs"),
            ("settlement/entity/humanoid/ai/types/parent/AIModule_Parent.cs", "Scripts/Citizens/CitizenReproductionRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/room/service/nursery/NurseryInstance.cs", "Scripts/Rooms/ChildcareRuntime.cs"),
            ("settlement/room/service/nursery/NurseryStation.cs", "Scripts/Rooms/ChildcareRuntime.cs"),
            ("settlement/room/service/nursery/ROOM_NURSERY.cs", "Scripts/Rooms/ChildcareRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/service/breeder/BreederInstance.cs", "Scripts/Rooms/ChildcareRuntime.cs"),
            ("settlement/room/service/breeder/Station.cs", "Scripts/Rooms/ChildcareRuntime.cs"),
            ("settlement/room/service/breeder/ROOM_BREEDER.cs", "Scripts/Rooms/ChildcareRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/stats/colls/StatsEducation.cs", "Scripts/Citizens/CitizenPersonalStatsRuntime.cs; Scripts/Rooms/SchoolRuntime.cs"),
            ("settlement/room/knowledge/school/RoomEducationHelper.cs", "Scripts/Rooms/SchoolRuntime.cs; Scripts/Citizens/CitizenPersonalStatsRuntime.cs"),
            ("settlement/room/knowledge/school/SchoolInstance.cs", "Scripts/Rooms/SchoolRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/knowledge/school/SchoolStation.cs", "Scripts/Rooms/SchoolRuntime.cs"),
            ("settlement/room/knowledge/school/ROOM_SCHOOL.cs", "Scripts/Rooms/SchoolRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/room/service/hygine/bath/Bath.cs", "Scripts/Rooms/BathRuntime.cs; Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/room/service/hygine/bath/BathInstance.cs", "Scripts/Rooms/BathRuntime.cs"),
            ("settlement/room/service/hygine/bath/Bits.cs", "Scripts/Rooms/BathRuntime.cs"),
            ("settlement/room/service/hygine/bath/Crank.cs", "Scripts/Rooms/BathRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/service/hygine/bath/Oven.cs", "Scripts/Rooms/BathRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/service/hygine/bath/ROOM_BATH.cs", "Scripts/Rooms/BathRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/room/service/hygine/well/ROOM_WELL.cs", "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/room/service/hygine/well/Wash.cs", "Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/room/service/hygine/well/WellInstance.cs", "Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/room/service/hearth/Hearth.cs", "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/room/service/hearth/HearthInstance.cs", "Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/room/health/asylum/AsylumInstance.cs", "Scripts/Rooms/AsylumRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/health/asylum/Cell.cs", "Scripts/Rooms/AsylumRuntime.cs"),
            ("settlement/room/health/asylum/Food.cs", "Scripts/Rooms/AsylumRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/health/asylum/ROOM_ASYLUM.cs", "Scripts/Rooms/AsylumRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/entity/humanoid/ai/types/insane/AIModule_Insane.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/AsylumRuntime.cs"),
            ("settlement/room/food/cannibal/Cage.cs", "Scripts/Rooms/CannibalRuntime.cs"),
            ("settlement/room/food/cannibal/CannibalInstance.cs", "Scripts/Rooms/CannibalRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/food/cannibal/Job.cs", "Scripts/Rooms/CannibalRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/food/cannibal/ROOM_CANNIBAL.cs", "Scripts/Rooms/CannibalRuntime.cs; Scripts/Law/SettlementLawRuntime.cs"),
            ("settlement/entity/humanoid/ai/types/prisoner/ExecuteCannibal.cs", "Scripts/Law/SettlementLawRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/entity/humanoid/ai/work/WorkCannibal.cs", "Scripts/Rooms/CannibalRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/infra/janitor/BITS.cs", "Scripts/Rooms/JanitorRuntime.cs"),
            ("settlement/room/infra/janitor/JM.cs", "Scripts/Rooms/JanitorRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/infra/janitor/JanitorInstance.cs", "Scripts/Rooms/JanitorRuntime.cs"),
            ("settlement/room/infra/janitor/ROOM_JANITOR.cs", "Scripts/Rooms/JanitorRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/service/arena/grand/ArenaInstance.cs", "Scripts/Rooms/ActivityServiceRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/service/arena/RoomArenaWork.cs", "Scripts/Rooms/ActivityServiceRuntime.cs; Scripts/Rooms/AsylumRuntime.cs"),
            ("settlement/room/service/arena/grand/ROOM_ARENA.cs", "Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/arena/grand/Service.cs", "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/arena/pit/ArenaInstance.cs", "Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/arena/pit/ROOM_FIGHTPIT.cs", "Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/arena/pit/Service.cs", "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/speaker/Centre.cs", "Scripts/Rooms/ActivityServiceRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/service/speaker/ROOM_SPEAKER.cs", "Scripts/Rooms/ActivityServiceRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/service/speaker/SpeakerInstance.cs", "Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/stage/Centre.cs", "Scripts/Rooms/ActivityServiceRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/service/stage/StageInstance.cs", "Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/barber/Instance.cs", "Scripts/Rooms/PreparedServiceRuntime.cs"),
            ("settlement/room/service/barber/ROOM_BARBER.cs", "Scripts/Rooms/PreparedServiceRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/room/service/barber/Tile.cs", "Scripts/Rooms/PreparedServiceRuntime.cs; Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/room/health/physician/Instance.cs", "Scripts/Rooms/PreparedServiceRuntime.cs"),
            ("settlement/room/health/physician/Service.cs", "Scripts/Rooms/PreparedServiceRuntime.cs; Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/entity/humanoid/ai/service/M_PlanPhysician.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/PreparedServiceRuntime.cs"),
            ("settlement/room/service/food/canteen/CanteenInstance.cs", "Scripts/Rooms/FoodVenueRuntime.cs"),
            ("settlement/room/service/food/canteen/SService.cs", "Scripts/Rooms/FoodVenueRuntime.cs; Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/room/service/food/canteen/SWork.cs", "Scripts/Rooms/FoodVenueRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/service/food/eatery/EateryInstance.cs", "Scripts/Rooms/FoodVenueRuntime.cs"),
            ("settlement/room/service/food/eatery/ROOM_EATERY.cs", "Scripts/Rooms/FoodVenueRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/room/service/food/tavern/ROOM_TAVERN.cs", "Scripts/Rooms/FoodVenueRuntime.cs"),
            ("settlement/room/service/food/tavern/TavernInstance.cs", "Scripts/Rooms/FoodVenueRuntime.cs"),
            ("settlement/room/service/pleasure/ABed.cs", "Scripts/Rooms/PreparedServiceRuntime.cs; Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/room/service/pleasure/PleasureInstance.cs", "Scripts/Rooms/PreparedServiceRuntime.cs"),
            ("settlement/room/service/pleasure/ROOM_PLEASURE.cs", "Scripts/Rooms/PreparedServiceRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/entity/humanoid/ai/service/M_PlanBrothel.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/PreparedServiceRuntime.cs"),
            ("settlement/stats/colls/StatsAccess.cs", "Scripts/Stats/SettlementStatsRuntime.cs"),
            ("settlement/stats/colls/StatsBurial.cs", "Scripts/Stats/SettlementStatsRuntime.cs; Scripts/Rooms/BurialRuntime.cs"),
            ("settlement/stats/colls/StatsEnv.cs", "Scripts/Stats/SettlementStatsRuntime.cs; Scripts/Citizens/CorpseRuntime.cs"),
            ("settlement/stats/colls/StatsFood.cs", "Scripts/Stats/SettlementStatsRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/stats/colls/StatsStored.cs", "Scripts/Stats/SettlementStatsRuntime.cs; Scripts/Resources/ResourceLedger.cs"),
            ("settlement/entity/humanoid/ai/service/S_Plan.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/RoomServiceRuntime.cs"),
            ("settlement/entity/humanoid/ai/service/S_PlanEntertain.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/entity/humanoid/ai/service/M_PlanSpectator.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/module/ROOM_ACTIVITY.cs", "Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/room/service/module/ROOM_SPECTATOR.cs", "Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/stats/colls/StatsNeeds.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/stats/colls/StatsPopulation.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Stats/SettlementStatsRuntime.cs"),
            ("settlement/stats/colls/StatsWork.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/RoomEmploymentRuntime.cs"),
            ("settlement/stats/colls/StatsReligion.cs", "Scripts/Citizens/ReligionRuntime.cs; Scripts/Stats/SettlementStatsRuntime.cs"),
            ("settlement/stats/colls/StatsHome.cs", "Scripts/Rooms/HousingRuntime.cs; Scripts/Stats/SettlementStatsRuntime.cs"),
            ("init/race/home/RaceHome.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Rooms/HousingRuntime.cs"),
            ("init/race/home/RaceHomeClass.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Rooms/HousingRuntime.cs"),
            ("init/race/home/RaceHomeSheet.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Rooms/HousingRuntime.cs"),
            ("settlement/entity/humanoid/ai/home/AIModule_Home.cs", "Scripts/Citizens/HomeBehaviorRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/entity/humanoid/ai/home/PlanReturn.cs", "Scripts/Rooms/HousingRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/home/HOME.cs", "Scripts/Rooms/HousingRuntime.cs"),
            ("settlement/room/home/house/HomeInstance.cs", "Scripts/Rooms/HousingRuntime.cs"),
            ("settlement/room/home/house/ROOM_HOME.cs", "Scripts/Rooms/HousingRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/home/house/HomeContructor.cs", "Scripts/Rooms/HousingRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/home/house/OddHome.cs", "Scripts/Rooms/HousingRuntime.cs"),
            ("settlement/room/home/chamber/ChamberInstance.cs", "Scripts/Rooms/HousingRuntime.cs"),
            ("settlement/room/home/chamber/ROOM_CHAMBER.cs", "Scripts/Rooms/HousingRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/home/chamber/Constructor.cs", "Scripts/Rooms/HousingRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/home/chamber/Work.cs", "Scripts/Rooms/HousingRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/entity/humanoid/ai/subject/Activity.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/entity/humanoid/ai/subject/ActivityMourn.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/BurialRuntime.cs"),
            ("settlement/entity/humanoid/ai/subject/AIModule_Subject.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/BurialRuntime.cs; Scripts/Rooms/ActivityServiceRuntime.cs"),
            ("settlement/stats/colls/StatsBattle.cs", "Scripts/Citizens/CitizenPersonalStatsRuntime.cs; Scripts/Stats/SettlementStatsRuntime.cs"),
            ("settlement/stats/colls/StatsEducation.cs", "Scripts/Citizens/CitizenPersonalStatsRuntime.cs; Scripts/Stats/SettlementStatsRuntime.cs"),
            ("settlement/stats/colls/StatsTraits.cs", "Scripts/Citizens/CitizenPersonalStatsRuntime.cs"),
            ("settlement/room/food/fish/BoatMaker.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Settlement/WorldGridData.cs"),
            ("settlement/room/food/fish/Constructor.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/food/fish/FishInstance.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/food/fish/Job.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/food/fish/ROOM_FISHERY.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/room/food/hunter/Constructor.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/food/hunter/HunterInstance.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/food/hunter/Job.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/food/hunter/ROOM_HUNTER.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/room/food/hunter/Tile.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/food/orchard/Constructor.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/food/orchard/Instance.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/food/orchard/OTile.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/food/orchard/ROOM_ORCHARD.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/room/food/pasture/Constructor.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/food/pasture/ConstructorIndoor.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/food/pasture/ConstructorOutdoor.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/food/pasture/JobManager.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/food/pasture/PastureInstance.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/food/pasture/ROOM_PASTURE.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/room/industry/woodcutter/Constructor.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/FurnisherRuntime.cs"),
            ("settlement/room/industry/woodcutter/Instance.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/room/industry/woodcutter/Job.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Simulation/BuildJob.cs"),
            ("settlement/room/industry/woodcutter/ROOM_WOODCUTTER.cs", "Scripts/Rooms/SpecialProductionRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/tilemap/generator/Generator.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs"),
            ("settlement/tilemap/generator/GeneratorFertilityInit.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs; Scripts/Settlement/WorldGridData.cs"),
            ("settlement/tilemap/generator/GeneratorFertilityFin.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs; Scripts/Settlement/WorldGridData.cs"),
            ("settlement/tilemap/generator/GeneratorMinerals.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/tilemap/ground/Ground.cs", "Scripts/Settlement/WorldGridData.cs"),
            ("settlement/tilemap/ground/Minables.cs", "Scripts/Settlement/WorldGridData.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/tilemap/generator/GeneratorWaterFin.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs; Scripts/Settlement/WorldGridData.cs"),
            ("settlement/tilemap/generator/GeneratorOcean.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs; Scripts/Settlement/WorldGridData.cs"),
            ("settlement/tilemap/generator/GeneratorGrowth.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs; Scripts/Settlement/WorldGridData.cs"),
            ("settlement/tilemap/generator/GeneratorEdibles.cs", "Scripts/Settlement/SettlementTerrainGenerator.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/environment/ENVIRONMENT.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Settlement/SettlementTerrainGenerator.cs"),
            ("settlement/environment/Foundation.cs", "Scripts/Settlement/WorldGridData.cs; Scripts/Settlement/SettlementTerrainGenerator.cs"),
            ("settlement/weather/SWEATHER.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs; Scripts/Bootstrap/GameBootstrap.cs"),
            ("settlement/weather/WeatherThing.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("settlement/weather/WeatherMoisture.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            ("settlement/weather/WeatherTemp.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs; Scripts/Data/OriginalGameData.cs"),
            ("settlement/weather/WeatherDownfall.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("settlement/weather/WeatherSnow.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("settlement/weather/WeatherIce.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("settlement/weather/WeatherGrowth.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("settlement/weather/WeatherGrowthRipe.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("settlement/weather/WeatherClouds.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("settlement/weather/WeatherWind.cs", "Scripts/Simulation/SettlementWeatherRuntime.cs"),
            ("init/race/Race.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("init/race/RACES.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("init/race/RaceInfo.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("init/race/RacePopulation.cs", "Scripts/Data/OriginalGameData.cs"),
            ("init/race/RacePreferrence.cs", "Scripts/Data/OriginalGameData.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("init/type/HCLASS.cs", "Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("init/type/HCLASSES.cs", "Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("init/type/HTYPE.cs", "Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("init/type/HTYPES.cs", "Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("init/type/HCLASS_RACE.cs", "Scripts/Citizens/CitizenIdentityRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("init/type/HGROUP.cs", "Scripts/Citizens/CitizenIdentityRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/stats/Induvidual.cs", "Scripts/Citizens/CitizenIdentityRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/entry/EntryPoints.cs", "Scripts/Settlement/SettlementEntryRuntime.cs"),
            ("settlement/entry/EntryUpdater.cs", "Scripts/Settlement/SettlementEntryRuntime.cs; Scripts/Settlement/GridWorld.cs"),
            ("settlement/entry/PeopleSpawner.cs", "Scripts/Settlement/SettlementEntryRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("settlement/entry/SENTRY.cs", "Scripts/Settlement/SettlementEntryRuntime.cs; Scripts/Bootstrap/GameBootstrap.cs"),
            ("settlement/entry/Immigration.cs", "Scripts/Settlement/ImmigrationRuntime.cs; Scripts/Settlement/SettlementEntryRuntime.cs"),
            ("settlement/entity/humanoid/ai/subject/PlanEmmigrate.cs", "Scripts/Citizens/CitizenSystem.cs; Scripts/Settlement/SettlementEntryRuntime.cs"),
            ("settlement/path/finders/SFinderEntry.cs", "Scripts/Settlement/SettlementEntryRuntime.cs"),
            ("init/type/CAUSE_ARRIVE.cs", "Scripts/Settlement/SettlementEntryRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("init/type/CAUSE_ARRIVES.cs", "Scripts/Settlement/SettlementEntryRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("init/type/CAUSE_LEAVE.cs", "Scripts/Settlement/SettlementEntryRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            ("init/type/CAUSE_LEAVES.cs", "Scripts/Settlement/SettlementEntryRuntime.cs; Scripts/Citizens/CitizenSystem.cs"),
            # Stage 7: one shared data-driven logistics/trade runtime replaces the
            # duplicated Java room crates, tallies, pull orders and player traders.
            *[(path, "Scripts/Rooms/SettlementLogisticsRuntime.cs; Scripts/Hauling/HaulingSystem.cs; Scripts/Simulation/BuildJob.cs") for path in (
                "settlement/room/infra/stockpile/Crate.cs",
                "settlement/room/infra/stockpile/Organiser.cs",
                "settlement/room/infra/stockpile/ROOM_STOCKPILE.cs",
                "settlement/room/infra/stockpile/StockpileInstance.cs",
                "settlement/room/infra/stockpile/StockpileTally.cs",
                "settlement/room/infra/hauler/Crate.cs",
                "settlement/room/infra/hauler/HaulerInstance.cs",
                "settlement/room/infra/hauler/HaulerTally.cs",
                "settlement/room/infra/hauler/ROOM_HAULER.cs",
                "settlement/room/infra/transport/Cart.cs",
                "settlement/room/infra/transport/Job.cs",
                "settlement/room/infra/transport/ROOM_TRANSPORT.cs",
                "settlement/room/infra/transport/TransportInstance.cs",
                "settlement/room/infra/export/Crate.cs",
                "settlement/room/infra/export/ExportFetcher.cs",
                "settlement/room/infra/export/ExportInstance.cs",
                "settlement/room/infra/export/ExportTally.cs",
                "settlement/room/infra/export/ROOM_EXPORT.cs",
                "settlement/room/infra/importt/Crate.cs",
                "settlement/room/infra/importt/ImportInstance.cs",
                "settlement/room/infra/importt/ImportTally.cs",
                "settlement/room/infra/importt/ImportThingy.cs",
                "settlement/room/infra/importt/ROOM_IMPORT.cs",
                "settlement/room/infra/logistics/MoveDic.cs",
                "settlement/room/infra/logistics/MoveJob.cs",
                "settlement/room/infra/logistics/MoveOrderPull.cs",
                "settlement/room/infra/logistics/MoveOrderPush.cs",
                "settlement/room/service/market/MarketInstance.cs",
                "settlement/room/service/market/ROOM_MARKET.cs",
            )],
            *[(path, "Scripts/Trade/SettlementTradeRuntime.cs; Scripts/Rooms/SettlementLogisticsRuntime.cs") for path in (
                "settlement/trade/PBuyer.cs",
                "settlement/trade/PBuyerRes.cs",
                "settlement/trade/PBuyerSlave.cs",
                "settlement/trade/PSeller.cs",
                "settlement/trade/PSellerRes.cs",
                "settlement/trade/PSellerSlave.cs",
                "settlement/trade/SettTrade.cs",
                "settlement/trade/TradableData.cs",
                "game/faction/trade/FBUYER.cs",
                "game/faction/trade/FSELLER.cs",
                "game/faction/trade/ResourcePrices.cs",
                "game/faction/trade/TradeManager.cs",
                "game/faction/trade/TradeShipper.cs",
                "game/faction/trade/TradeSorter.cs",
            )],
            *[(path, "Scripts/Data/OriginalGameData.cs; Scripts/Technology/TechnologyRuntime.cs") for path in (
                "init/tech/TECH.cs",
                "init/tech/TECHS.cs",
                "init/tech/TechCost.cs",
                "init/tech/TechCurrency.cs",
                "init/tech/TechTree.cs",
            )],
            *[(path, "Scripts/Rooms/KnowledgeRuntime.cs; Scripts/Rooms/RoomSystem.cs") for path in (
                "settlement/room/knowledge/laboratory/LaboratoryInstance.cs",
                "settlement/room/knowledge/laboratory/ROOM_LABORATORY.cs",
                "settlement/room/knowledge/library/LibraryInstance.cs",
                "settlement/room/knowledge/library/ROOM_LIBRARY.cs",
                "settlement/room/knowledge/university/Job.cs",
                "settlement/room/knowledge/university/ROOM_UNIVERSITY.cs",
                "settlement/room/knowledge/university/UniversityInstance.cs",
                "settlement/room/industry/module/consumption/ConsumptionJob.cs",
                "settlement/room/industry/module/consumption/RoomConsumption.cs",
                "settlement/room/industry/module/consumption/RoomConsumptionAbs.cs",
                "settlement/room/infra/admin/AdminData.cs",
            )],
            *[(path, "Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/KnowledgeRuntime.cs") for path in (
                "settlement/entity/humanoid/ai/types/student/AIModule_Student.cs",
                "settlement/entity/humanoid/ai/types/student/Plan.cs",
            )],
            # Stage 9: law data, statistics, room services and guard/criminal plans are
            # consolidated into one case/facility runtime instead of compiling the
            # translated Java bit fields and per-room job hierarchies.
            *[(path.relative_to(LEGACY).as_posix(),
               "Scripts/Law/SettlementLawRuntime.cs; Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/RoomSystem.cs")
              for prefix in (
                  "settlement/stats/law", "settlement/room/law",
                  "settlement/entity/humanoid/ai/crime",
                  "settlement/entity/humanoid/ai/types/guard",
                  "settlement/entity/humanoid/ai/types/prisoner")
              for path in sorted((LEGACY / prefix).rglob("*.cs"))
              if not any(part in path.name for part in ("Gui", "UI", "Renderer", "Constructor", "Placer"))],
            *[(path, "Scripts/Data/OriginalGameData.cs; Scripts/Law/SettlementLawRuntime.cs") for path in (
                "init/type/CRIMES.cs",
                "init/type/CRIME_PUNISHMENTS.cs",
            )],
            # Stage 10 settlement governance. Royal courts/emissaries remain a world-layer
            # boundary, but player progression, treasury, local administration and nobility
            # are represented by shared data-driven runtimes.
            *[(path, "Scripts/Governance/SettlementGovernanceRuntime.cs; Scripts/Data/OriginalGameData.cs") for path in (
                "game/nobility/Init.cs",
                "game/nobility/NOBLES.cs",
                "game/nobility/Noble.cs",
                "game/nobility/NobleOffice.cs",
                "game/nobility/NobleOfficeUtil.cs",
                "game/faction/player/PTech.cs",
                "game/faction/player/PTitles.cs",
                "game/faction/player/BoostCompound.cs",
                "game/faction/player/PBonusSetting.cs",
                "game/faction/player/PCredits.cs",
                "game/faction/player/PLevels.cs",
                "game/faction/player/PTrade.cs",
                "game/faction/player/Player.cs",
            )],
            *[(path, "Scripts/Governance/SettlementGovernanceRuntime.cs; Scripts/Rooms/RoomSystem.cs; Scripts/Rooms/KnowledgeRuntime.cs") for path in (
                "settlement/room/infra/admin/AdminInstance.cs",
                "settlement/room/infra/admin/ROOM_ADMIN.cs",
                "settlement/room/infra/embassy/EmbassyInstance.cs",
                "settlement/room/infra/embassy/ROOM_EMBASSY.cs",
                "settlement/room/infra/monument/Imp.cs",
                "settlement/room/infra/monument/ROOM_MONUMENT.cs",
                "settlement/room/infra/monument/ROOM_MONUMENTS.cs",
                "settlement/room/infra/monument/Torch.cs",
                "settlement/room/main/throne/Initer.cs",
                "settlement/room/main/throne/Instance.cs",
                "settlement/room/main/throne/InstanceConstruction.cs",
                "settlement/room/main/throne/THRONE.cs",
                "settlement/entity/humanoid/ai/types/noble/AIModule_Noble.cs",
            )],
            # Stage 11: local division rosters, recruit training, military depots and
            # artillery are consolidated here. Invasion presentation and battlefield
            # target selection stay pending until the settlement battle layer exists.
            *[(path, "Scripts/Military/SettlementMilitaryRuntime.cs; Scripts/Citizens/CitizenSystem.cs; Scripts/Rooms/RoomSystem.cs") for path in (
                "settlement/room/military/artillery/ROOM_ARTILLERY.cs",
                "settlement/room/military/artillery/ArtilleryInstance.cs",
                "settlement/room/military/artillery/Service.cs",
                "settlement/room/military/supply/Cache.cs",
                "settlement/room/military/supply/Crate.cs",
                "settlement/room/military/supply/ROOM_SUPPLY.cs",
                "settlement/room/military/supply/SupplyInstance.cs",
                "settlement/room/military/supply/SupplyTally.cs",
                "settlement/room/military/training/ROOM_M_TRAINER.cs",
                "settlement/room/military/training/archery/ArcheryInstance.cs",
                "settlement/room/military/training/archery/ArcheryThing.cs",
                "settlement/room/military/training/archery/ROOM_ARCHERY.cs",
                "settlement/room/military/training/barracks/BarracksInstance.cs",
                "settlement/room/military/training/barracks/BarracksThing.cs",
                "settlement/room/military/training/barracks/ROOM_BARRACKS.cs",
                "settlement/entity/humanoid/ai/types/recruit/AIModule_Recruit.cs",
                "settlement/entity/humanoid/ai/types/recruit/PlanBarracks.cs",
                "settlement/entity/humanoid/ai/types/recruit/PlanRange.cs",
                "game/battle/div/Div.cs",
                "game/battle/div/DivInfo.cs",
                "game/battle/div/DivMen.cs",
            )],
            # Stage 12: the source event grammar and settlement event families share
            # one simulation runtime. Only the debug UI, action-constructor wiring and
            # already-ported workplace accident scheduler are excluded from this batch.
            *[(source.relative_to(LEGACY).as_posix(),
               "Scripts/Events/SettlementEventRuntime.cs; Scripts/Citizens/CitizenSystem.cs; Scripts/Bootstrap/GameBootstrap.cs")
              for prefix in (
                  "game/event/engine", "game/event/actions", "game/events/citizen",
                  "game/events/disaster", "game/events/killer", "game/events/slave",
                  "settlement/entity/humanoid/ai/types/rioter")
              for source in sorted((LEGACY / prefix).glob("*.cs"))
              if source.name not in {"UIEventDebug.cs", "EventActionConstructor.cs", "EventAccident.cs"}],
            # Stage 13: non-combat humanoid planning is represented by the dense citizen
            # loop, shared job/service consumers and relationship runtime. Battle plans
            # and special Retiree/Deranged/Tourist lifecycles remain deliberately pending.
            *[(source.relative_to(LEGACY).as_posix(),
               "Scripts/Citizens/CitizenSystem.cs; Scripts/Citizens/CitizenSocialRuntime.cs; Scripts/Simulation/JobBoard.cs; Scripts/Rooms/RoomServiceRuntime.cs")
              for prefix in (
                  "settlement/entity/humanoid/ai/main",
                  "settlement/entity/humanoid/ai/consume",
                  "settlement/entity/humanoid/ai/danger",
                  "settlement/entity/humanoid/ai/idle",
                  "settlement/entity/humanoid/ai/subwalk",
                  "settlement/entity/humanoid/ai/util",
                  "settlement/entity/humanoid/ai/work",
                  "settlement/entity/humanoid/ai/service")
              for source in sorted((LEGACY / prefix).glob("*.cs"))],
            ("settlement/entity/humanoid/ai/types/slave/AIModule_Slave.cs",
             "Scripts/Citizens/CitizenSystem.cs; Scripts/Citizens/CitizenSocialRuntime.cs"),
            ("settlement/stats/colls/StatsAppearance.cs",
             "Scripts/Citizens/CitizenIdentityRuntime.cs"),
            ("settlement/stats/colls/StatsGovern.cs",
             "Scripts/Governance/SettlementGovernanceRuntime.cs; Scripts/Stats/SettlementStatsRuntime.cs"),
            # Stage 14: water infrastructure and the already shared agriculture,
            # industry, service, equipment and statistics adapters. Visual constructors,
            # sprites and room panels intentionally remain outside the compiled runtime.
            *[(path, "Scripts/Rooms/WaterInfrastructureRuntime.cs; Scripts/Rooms/RoomSystem.cs; Scripts/Settlement/WorldGridData.cs") for path in (
                "settlement/room/water/Canal.cs",
                "settlement/room/water/Drain.cs",
                "settlement/room/water/PumpInstance.cs",
                "settlement/room/water/PumpJob.cs",
                "settlement/room/water/ROOM_PUMP.cs",
                "settlement/room/water/ROOM_WATER.cs",
                "settlement/room/water/RoomIrrigated.cs",
                "settlement/room/water/RoomPumpable.cs",
                "settlement/room/water/Updater.cs",
                "settlement/room/water/pool/ROOM_POOL.cs",
            )],
            ("settlement/room/infra/gate/ROOM_GATE.cs",
             "Scripts/Rooms/GateRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            *[(path, "Scripts/Rooms/SettlementLogisticsRuntime.cs; Scripts/Rooms/RoomSystem.cs") for path in (
                "settlement/room/infra/station/Crate.cs",
                "settlement/room/infra/station/Job.cs",
                "settlement/room/infra/station/ROOM_STATION.cs",
                "settlement/room/infra/station/StationInstance.cs",
                "settlement/room/infra/station/StationTally.cs",
            )],
            *[(path, "Scripts/Rooms/HospitalityRuntime.cs; Scripts/Rooms/RoomSystem.cs; Scripts/Citizens/CitizenSystem.cs") for path in (
                "settlement/room/infra/elderly/Job.cs",
                "settlement/room/infra/elderly/ResthomeInstance.cs",
                "settlement/room/infra/elderly/ROOM_RESTHOME.cs",
                "settlement/room/infra/inn/ABed.cs",
                "settlement/room/infra/inn/ROOM_INN.cs",
                "settlement/room/infra/inn/InnInstance.cs",
            )],
            *[(path, "Scripts/Rooms/BuilderInfrastructureRuntime.cs; Scripts/Rooms/RoomSystem.cs") for path in (
                "settlement/room/infra/builder/BuilderInstance.cs",
                "settlement/room/infra/builder/ROOM_BUILDER.cs",
            )],
            *[(path, "Scripts/Stats/SettlementStatRegistry.cs; Scripts/Stats/SettlementStatsRuntime.cs; Scripts/Events/SettlementEventRuntime.cs") for path in (
                "settlement/stats/disease/BoostsHealth.cs",
                "settlement/stats/event/StatsEvent.cs",
                "settlement/stats/stat/DataRaces.cs",
                "settlement/stats/stat/STAT.cs",
                "settlement/stats/stat/STATData.cs",
                "settlement/stats/stat/STATFake.cs",
                "settlement/stats/stat/STATFakeData.cs",
                "settlement/stats/stat/STATFakeRace.cs",
                "settlement/stats/stat/STATInduOnly.cs",
                "settlement/stats/stat/StatCollection.cs",
                "settlement/stats/stat/StatDecree.cs",
                "settlement/stats/stat/StatInfo.cs",
                "settlement/stats/stat/StatObject.cs",
                "settlement/stats/util/StatBooster.cs",
                "settlement/stats/util/StatsJson.cs",
            )],
            *[(path, "Scripts/Rooms/RoomSystem.cs; Scripts/Industry/IndustryRuntime.cs") for path in (
                "settlement/room/industry/module/IndustryRegion.cs",
                "settlement/room/industry/module/RoomBoost.cs",
                "settlement/room/industry/module/RoomIndustries.cs",
                "settlement/room/industry/module/RoomProduction.cs",
                "settlement/room/industry/refiner/Job.cs",
                "settlement/room/industry/refiner/RefinerInstance.cs",
                "settlement/room/industry/workshop/Job.cs",
                "settlement/room/industry/workshop/ROOM_WORKSHOP.cs",
            )],
            *[(path, "Scripts/Rooms/BurialRuntime.cs; Scripts/Rooms/RoomSystem.cs") for path in (
                "settlement/room/spirit/grave/CGraveyard.cs",
                "settlement/room/spirit/grave/CTomb.cs",
                "settlement/room/spirit/grave/GraveInfo.cs",
            )],
            *[(path, "Scripts/Citizens/CitizenSystem.cs; Scripts/Citizens/CitizenIdentityRuntime.cs") for path in (
                "settlement/entity/humanoid/Humanoid.cs",
                "settlement/entity/humanoid/HEvent.cs",
                "settlement/entity/humanoid/HPoll.cs",
                "settlement/entity/humanoid/Humanoids.cs",
            )],
            *[(path, "Scripts/Rooms/RoomSystem.cs; Scripts/Rooms/RoomInstanceRuntime.cs; Scripts/Rooms/RoomPlacementRuntime.cs") for path in (
                "settlement/room/main/MapDataF.cs",
                "settlement/room/main/ROOMS.cs",
                "settlement/room/main/MapRoomData.cs",
                "settlement/room/main/RoomSingleton.cs",
                "settlement/room/main/RoomsMap.cs",
                "settlement/room/main/TmpArea.cs",
                "settlement/room/main/Updater.cs",
                "settlement/room/main/employment/Employer.cs",
                "settlement/room/main/job/ROOM_RADIUS.cs",
                "settlement/room/main/construction/CONSTRUCTION.cs",
                "settlement/room/main/construction/ConstructionData.cs",
                "settlement/room/main/placement/Instance.cs",
                "settlement/room/main/placement/PlacerItemArea.cs",
                "settlement/room/main/placement/PlacerItemSingle.cs",
                "settlement/room/main/placement/UtilExtraCost.cs",
                "settlement/room/main/placement/UtilHistory.cs",
                "settlement/room/main/placement/UtilStructure.cs",
                "settlement/room/main/placement/UtilWallPlacability.cs",
                "settlement/room/main/util/Deleter.cs",
                "settlement/room/main/util/RoomAreaWrapper.cs",
                "settlement/room/main/util/RoomBits.cs",
                "settlement/room/main/util/RoomIsolation.cs",
                "settlement/room/main/util/RoomStats.cs",
                "settlement/room/main/util/RoomTally.cs",
                "settlement/room/main/util/RoomUtil.cs",
                "settlement/room/main/util/RoomsCreator.cs",
            )],
            ("settlement/room/health/physician/ROOM_PHYSICIAN.cs",
             "Scripts/Rooms/PreparedServiceRuntime.cs; Scripts/Rooms/RoomSystem.cs"),
            *[(path, "Scripts/Rooms/RoomSystem.cs; Scripts/Settlement/WorldGridData.cs") for path in (
                "settlement/room/food/farm/ROOM_FARM.cs",
                "settlement/room/food/farm/Tile.cs",
                "settlement/room/food/farm/FarmInstance.cs",
                "settlement/room/food/farm/Time.cs",
                "settlement/room/food/farm/Util.cs",
                "settlement/room/industry/mine/MineInstance.cs",
                "settlement/room/industry/mine/ROOM_MINE.cs",
                "settlement/room/industry/module/INDUSTRY_HASER.cs",
                "settlement/room/industry/module/IndustryRate.cs",
                "settlement/room/industry/module/ROOM_IDATA_INSTANCE.cs",
                "settlement/room/industry/module/ROOM_PRODUCER_INSTANCE.cs",
                "settlement/room/industry/refiner/ROOM_REFINER.cs",
            )],
            *[(path, "Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Rooms/FoodVenueRuntime.cs; Scripts/Rooms/ActivityServiceRuntime.cs; Scripts/Rooms/RoomSystem.cs") for path in (
                "settlement/room/service/hearth/ROOM_HEARTH.cs",
                "settlement/room/service/module/ROOM_SERVICER.cs",
                "settlement/room/service/stage/ROOM_STAGE.cs",
                "settlement/room/service/arena/grand/CUtil.cs",
                "settlement/room/service/food/canteen/ROOM_CANTEEN.cs",
                "settlement/room/service/food/eatery/RoomDistribution.cs",
            )],
            *[(path, "Scripts/Stats/SettlementStatsRuntime.cs; Scripts/Rooms/RoomServiceRuntime.cs; Scripts/Citizens/CitizenSystem.cs") for path in (
                "settlement/stats/service/StatService.cs",
                "settlement/stats/service/StatServiceBench.cs",
                "settlement/stats/service/StatServiceChild.cs",
                "settlement/stats/service/StatServiceHospital.cs",
                "settlement/stats/service/StatServiceImp.cs",
                "settlement/stats/service/StatServiceRoom.cs",
                "settlement/stats/service/StatServiceSimple.cs",
                "settlement/stats/service/StatServiceSkinny.cs",
                "settlement/stats/service/StatsService.cs",
            )],
            *[(path, "Scripts/Rooms/RoomSystem.cs; Scripts/Military/SettlementMilitaryRuntime.cs; Scripts/Resources/ResourceLedger.cs") for path in (
                "settlement/stats/equip/Equip.cs",
                "settlement/stats/equip/EquipBattle.cs",
                "settlement/stats/equip/EquipCivic.cs",
                "settlement/stats/equip/EquipRange.cs",
                "settlement/stats/equip/StatsEquip.cs",
                "settlement/stats/equip/WearableResource.cs",
            )],
            *[(path, "Scripts/Stats/SettlementStatsRuntime.cs; Scripts/Citizens/CitizenSocialRuntime.cs; Scripts/Citizens/CitizenSystem.cs") for path in (
                "settlement/stats/STATS.cs",
                "settlement/stats/POP.cs",
                "settlement/stats/SValues.cs",
                "settlement/stats/StatsInit.cs",
                "settlement/stats/muls/StatsMultipliers.cs",
                "settlement/stats/relation/StatsRelations.cs",
                "settlement/stats/stat/SETT_STATISTICS.cs",
            )],
            *[(path, "Scripts/World/StrategicWorldRuntime.cs; Scripts/UI/StrategicWorldMap.cs; Scripts/Trade/SettlementTradeRuntime.cs") for path in (
                "world/region/Gen.cs",
                "world/region/RDDistance.cs",
                "game/faction/FACTIONS.cs",
                "game/faction/Faction.cs",
                "game/faction/diplomacy/DIP.cs",
                "game/faction/trade/TradeManager.cs",
            )],
            *[(path, "Scripts/World/RegionalEconomyRuntime.cs; Scripts/World/StrategicWorldRuntime.cs; Scripts/UI/StrategicWorldMap.cs") for path in (
                "world/region/building/RDBuildings.cs",
                "world/region/building/RDBuilding.cs",
                "world/region/building/RDBuildingLevel.cs",
                "world/region/building/Creator.cs",
                "world/region/pop/RDRaces.cs",
                "world/region/RDOutputs.cs",
                "world/region/updating/Shipper.cs",
            )],
            *[(path, "Scripts/World/RegionalEconomyRuntime.cs; Scripts/UI/StrategicWorldMap.cs") for path in (
                "world/region/RDProspects.cs",
                "world/region/pop/RDRace.cs",
                "world/entity/caravan/Shipment.cs",
                "world/entity/caravan/Shipments.cs",
            )],
            *[(path, "Scripts/World/RegionalEconomyRuntime.cs; Scripts/UI/StrategicWorldMap.cs; Scripts/Trade/SettlementTradeRuntime.cs") for path in (
                "world/region/pop/RDEdicts.cs",
                "game/faction/npc/stockpile/NPCStockpile.cs",
                "game/faction/npc/stockpile/NPCRes.cs",
            )],
            ("world/region/RDReligions.cs", "Scripts/Data/OriginalGameData.cs; Scripts/World/RegionalEconomyRuntime.cs; Scripts/UI/StrategicWorldMap.cs"),
            *[(path, "Scripts/World/StrategicTerrainRuntime.cs; Scripts/World/StrategicWorldRuntime.cs; Scripts/UI/StrategicWorldMap.cs") for path in (
                "world/map/terrain/Generator.cs",
                "world/map/terrain/GeneratorForest.cs",
                "world/map/terrain/GeneratorHeight.cs",
                "world/map/terrain/GeneratorMountains.cs",
                "world/map/terrain/GeneratorOcean.cs",
                "world/map/terrain/GeneratorRiver.cs",
                "world/map/terrain/GeneratorSeasoner.cs",
                "world/map/terrain/WorldClimate.cs",
                "world/map/terrain/WorldForest.cs",
                "world/map/terrain/WorldGround.cs",
                "world/map/terrain/WorldMountain.cs",
                "world/map/terrain/WorldTerrain.cs",
                "world/map/terrain/WorldTerrainInfo.cs",
                "world/map/terrain/WorldWater.cs",
            )],
            *[(path, "Scripts/World/StrategicWorldRuntime.cs; Scripts/World/RegionalEconomyRuntime.cs; Scripts/UI/StrategicWorldMap.cs") for path in (
                "world/map/road/Gen.cs",
                "world/map/road/GenRoad.cs",
                "world/map/road/GenPort.cs",
                "world/map/road/GenPlayer.cs",
                "world/map/road/WTRAV.cs",
                "world/map/road/WorldRoads.cs",
            )],
        )
    ],
]


def adaptations() -> list[dict]:
    """Keep earlier reviewed entries when rebuilding, then overlay this batch."""
    merged: dict[str, dict] = {}
    legacy_paths = {path.relative_to(LEGACY).as_posix() for path in LEGACY.rglob("*.cs")}
    manifest = PORTING / "legacy_compile_manifest.json"
    if manifest.exists():
        previous = json.loads(manifest.read_text(encoding="utf-8"))
        merged.update({item["legacy"]: item for item in previous.get("compiled_adaptations", [])
                       if item["legacy"] in legacy_paths})
    merged.update({item["legacy"]: item for item in COMPILED_ADAPTATIONS})
    return list(merged.values())


def main() -> None:
    broken_payload = json.loads((PORTING / "broken_files.json").read_text(encoding="utf-8"))
    broken = {item["path"]: item["reasons"] for item in broken_payload["files"]}
    compiled_adaptations = adaptations()
    adapted = {item["legacy"] for item in compiled_adaptations}
    files = []
    counts: dict[str, int] = {}
    for path in sorted(LEGACY.rglob("*.cs")):
        relative = path.relative_to(LEGACY).as_posix()
        if relative in adapted:
            status = "adapted_compiled_separately"
            reasons = []
        elif relative in broken:
            status = "recovery_required"
            reasons = broken[relative]
        elif relative.startswith(("snake2d/", "org/lwjgl/")):
            status = "engine_or_runtime_reference"
            reasons = []
        else:
            status = "reference_pending_semantic_port"
            reasons = []
        counts[status] = counts.get(status, 0) + 1
        files.append({"path": relative, "status": status, "reasons": reasons})

    payload = {
        "schema": 1,
        "policy": (
            "LegacySource is excluded from compilation. Only reviewed semantic adaptations "
            "under Scripts are compiled by the Godot project."
        ),
        "legacy_file_count": len(files),
        "counts": counts,
        "compiled_adaptations": compiled_adaptations,
        "files": files,
    }
    (PORTING / "legacy_compile_manifest.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
